template = "https://github.com/giellalt/template-lang-und"
rev_id = 85
template_sha = "9ed3df3b4a68b795ab2c3d59873602b657210547"

[replacements]
__REPO__ = "lang-nno-x-ext-apertium"
__UND2C__ = "nn"
__UNDEFINED__ = "Norwegian Nynorsk"
__UND__ = "nno"
