template = "https://github.com/giellalt/template-lang-und"
rev_id = 174
template_sha = "9adfddf1c24903287529424ab1d522b969b00b11"

[replacements]
__REPO__ = "lang-nno-x-ext-apertium"
__UND2C__ = "nn"
__UNDEFINED__ = "Norwegian Nynorsk"
__UND__ = "nno"
