template = "https://github.com/giellalt/template-lang-und"
rev_id = 93
template_sha = "76239a3aabbd1c3f9424021323d9979df3bff322"

[replacements]
__REPO__ = "lang-nno-x-ext-apertium"
__UND2C__ = "nn"
__UNDEFINED__ = "Norwegian Nynorsk"
__UND__ = "nno"
