template = "https://github.com/giellalt/template-lang-und"
rev_id = 94
template_sha = "394256fcef9a3b6e16ef5ca9f975cf674be26544"

[replacements]
__REPO__ = "lang-nno-x-ext-apertium"
__UND2C__ = "nn"
__UNDEFINED__ = "Norwegian Nynorsk"
__UND__ = "nno"
