template = "https://github.com/giellalt/template-lang-und"
rev_id = 147
template_sha = "94ba09b9aec29cb7c92e29ab6d715415f99f825e"

[replacements]
__REPO__ = "lang-nno-x-ext-apertium"
__UND2C__ = "nn"
__UNDEFINED__ = "Norwegian Nynorsk"
__UND__ = "nno"
