template = "https://github.com/giellalt/template-lang-und"
rev_id = 151
template_sha = "52213ce4ca8d6057a7e2ada1b6e2b79a11ebd004"

[replacements]
__REPO__ = "lang-nno-x-ext-apertium"
__UND2C__ = "nn"
__UNDEFINED__ = "Norwegian Nynorsk"
__UND__ = "nno"
