template = "https://github.com/giellalt/template-lang-und"
rev_id = 101
template_sha = "4e8cec0740306225ea834d6a2ce36f612bb6ef07"

[replacements]
__REPO__ = "lang-nno-x-ext-apertium"
__UND2C__ = "nn"
__UNDEFINED__ = "Norwegian Nynorsk"
__UND__ = "nno"
