template = "https://github.com/giellalt/template-lang-und"
rev_id = 129
template_sha = "2e88456406f3ce2d6ca72a0b9303c5a0f2afdede"

[replacements]
__REPO__ = "lang-nno-x-ext-apertium"
__UND2C__ = "nn"
__UNDEFINED__ = "Norwegian Nynorsk"
__UND__ = "nno"
